Allow editing launch.properties
flathub/org.ghidra_sre.Ghidra pull request #2
Opened 2021-02-13 23:22 UTC by refi64

This creates a new file `~/.var/app/org.ghidra_sre.Ghidra/config/ghidra.properties` which is linked to Ghidra's own `launch.properties`. In particular, making this editable allows for easy HiDPI support by changing the value of `sun.java2d.uiScale`.

2021-02-14 00:06 UTC, hadess requested changes
Looks good otherwise, please update the TODO file as well :)

2021-02-14 00:06 UTC, hadess commented on org.ghidra_sre.Ghidra.json
> +                        "[[ -f /var/config/ghidra.properties ]] || cp /app/lib/ghidra/support/launch.properties.orig /var/config/ghidra.properties",
Can you add a comment in the script itself explaining what you're doing here?

2021-04-07 09:51 UTC, erazemk commented
@hadess Do you mind if I create a new pull request with refi's commit and add the description myself, so that this PR can be merged?

2021-04-07 15:57 UTC, refi64 commented
Apologies for the massive delay, the comment was added now.

2021-04-15 11:33 UTC, hadess approved these changes

2021-04-15 11:34 UTC, hadess commented
@flathubbot build

2021-04-15 11:39 UTC, hadess commented
bot, build

2021-04-15 11:40 UTC, hadess commented
> @flathubbot build

I filed https://github.com/flathub/flathub/issues/2261 seeing as the bot makes me pass for a dummy

2021-04-15 12:16 UTC, merged